export const SHOW_ALL_STORIES = 'SHOW_ALL_STORIES'
export const SHOW_SINGLE_POST = 'SHOW_SINGLE_POST'
export const CLOSE_OVERLAY = 'CLOSE_OVERLAY'
export const CHANGE_CURRENT_STORY = 'CHANGE_CURRENT_STORY'
